run-name: biogrid.v3.4.157
A:
  data-name: biogrid.v3.4.157
  name: sc
  gi: ../../data/gi/biogrid/sc/sc-biogrid.v3.4.157-sls-std.tsv
  ppi: ../../data/ppi/biogrid/sc/sc-biogrid.v3.4.157-ppi-std.tsv
B:
  data-name: biogrid.v3.4.157
  name: sp
  gi: ../../data/gi/biogrid/sp/sp-biogrid.v3.4.157-sls-std.tsv
  ppi: ../../data/ppi/biogrid/sp/sp-biogrid.v3.4.157-ppi-std.tsv
homologs: ../../data/homologs/sc-sp/sc-sp-homologs.txt
sample-negs: True
