species-A: human
species-B: sc
A-ppi: ../../data/ppi/string-v9.1/human/ensembl-human-network.txt
B-ppi: ../../data/ppi/biogrid/sc/sc-biogrid.v3.4.157-ppi.tsv
A-to-B-homologs: ../../data/homologs/human-sc/human-sc.txt
n_landmarks: 400
xmax: 0.01
line_width: 3
font_size: 16
resnik-scores: /cbcb/lab/mdml/users/jason/resnik_scores/human-sc.npz
